byexample/byexample.py
byexample/cache.py
byexample/common.py
byexample/differ.py
byexample/executor.py
byexample/expected.py
byexample/finder.py
byexample/init.py
byexample/jobs.py
byexample/log.py
byexample/modules/progress.py
byexample/modules/python.py
byexample/parser.py

Logging refactor

---

docs/advanced/greedy-lazy-tags.md

Documentation only changes that I noticed while I was reading the usage instructions.

Fix typos in greedy-lazy-tags.md

---

docs/advanced/shebang.md

Some more typos...
If I can find time I'll try go through the rest of the files and combine several commits into a single PR

Fix typos in shebang.md

---

docs/advanced/conditional-execution.md
docs/advanced/geometry.md
docs/advanced/terminal-emulation.md
docs/advanced/unicode.md

Suggested changes to the advanced docs

Grammar and typo fixes in advanced docs

---

byexample/executor.py
byexample/log.py
byexample/modules/elixir.py
byexample/runner.py
docs/_includes/idx.html
docs/advanced/geometry.md
docs/advanced/terminal-emulation.md
docs/languages/elixir.md
test/Dockerfile
test/docker.env

Elixir support

---

.gitignore
byexample/modules/python.py
docs/_includes/idx.html
docs/recipes/django-integration.md

Config prompts in python inside session

---

byexample/cmdline.py
byexample/init.py
byexample/runner.py
docs/_includes/idx.html
docs/advanced/echo-filtering.md

Make option for echo filter

---

.travis.yml

Run a smoke tests for OSX/macOS

---

byexample/common.py
byexample/differ.py
byexample/expected.py
byexample/finder.py
byexample/modules/clipboard.py
byexample/modules/cond.py
byexample/modules/cpp.py
byexample/modules/delimiters.py
byexample/modules/elixir.py
byexample/modules/gdb.py
byexample/modules/javascript.py
byexample/modules/php.py
byexample/modules/python.py
byexample/modules/ruby.py
byexample/modules/shell.py
byexample/parser.py
byexample/parser_sm.py
byexample/regex.py
byexample/runner.py
docs/contrib/how-to-define-new-zones-where-to-find-examples.md
docs/contrib/how-to-support-new-finders-and-languages.md
setup.py
test/Dockerfile

Issue 128 replace regex engine

---

Makefile
byexample/byexample.py
byexample/cfg.py
byexample/common.py
byexample/finder.py
byexample/init.py
byexample/jobs.py
byexample/log.py
byexample/modules/progress.py
docs/contrib/how-to-define-new-zones-where-to-find-examples.md
docs/contrib/how-to-hook-to-events-with-concerns.md
docs/contrib/how-to-support-new-finders-and-languages.md
test/corner.env
test/corner_cases.md

Issue 131 multithreading implementation

---

Makefile
byexample/modules/python.py
docs/_includes/idx.html
docs/languages/python.md
docs/recipes/python-doctest.md
test/ds/doctest-hard-diff.md

Issue 10 explicit doctest example

---

byexample/finder.py
byexample/modules/progress.py
test/corner_cases.md
test/ds/ascii_with_unicode_example.md

Issue #77: suggest --encoding flag if UnicodeDecodeError arises

---

byexample/init.py
byexample/modules/python.py
byexample/parser.py
byexample/runner.py
docs/contrib/how-to-support-new-finders-and-languages.md
docs/languages/python.md

Issue 113 use python3 for tests in python

---

byexample/runner.py
docs/overview/faq.md

Issue 11 show cmdline

---

.gitignore
README.md
byexample/cmdline.py
byexample/executor.py
byexample/modules/delimiters.py
docs/overview/where-should-I-write-the-examples.md
test/corner_cases.md

Issue 107 glob patterns

---

byexample/example.py
byexample/expected.py
byexample/finder.py
byexample/init.py
byexample/options.py
byexample/parser.py
docs/basic/input.md
docs/contrib/how-to-support-new-finders-and-languages.md
test/ds/maximum-ctx-input.md
test/ds/minimum-ctx-input.md

Issue #169: make +type an alias of +input flag.

---

.github/workflows/test.yml
Makefile
byexample/modules/cpp.py
byexample/modules/delimiters.py
byexample/modules/java.py
byexample/modules/rust.py
byexample/runner.py
docs/_includes/idx.html
docs/examples/java.java
docs/languages/java.md
test/lang-java.env

Issue 194 support java

---

byexample/example.py
byexample/expected.py
byexample/finder.py
byexample/init.py
byexample/modules/python.py
byexample/parser.py
byexample/parser_sm.py
docs/basic/capture-and-paste.md
docs/contrib/how-to-support-new-finders-and-languages.md
docs/languages/cpp.md
docs/languages/elixir.md
docs/languages/gdb.md
docs/languages/go.md
docs/languages/iasm.md
docs/languages/javascript.md
docs/languages/php.md
docs/languages/powershell.md
docs/languages/python.md
docs/languages/ruby.md
docs/languages/rust.md
docs/languages/shell.md
docs/overview/faq.md

Issue 199 disable named capture tags

---

.pre-commit-config.yaml
byexample/example.py
docs/recipes/python-doctest.md
test/corner_cases.md

Issue 204 install pre commits hooks for dev

---

byexample/modules/cpp.py
byexample/modules/elixir.py
byexample/modules/gdb.py
byexample/modules/go.py
byexample/modules/iasm.py
byexample/modules/java.py
byexample/modules/javascript.py
byexample/modules/php.py
byexample/modules/powershell.py
byexample/modules/python.py
byexample/modules/ruby.py
byexample/modules/rust.py
byexample/modules/shell.py
byexample/runner.py
docs/overview/faq.md
test/lang-cpp.env
test/lang-elixir.env
test/lang-gdb.env
test/lang-go.env
test/lang-iasm.env
test/lang-java.env
test/lang-javascript.env
test/lang-php.env
test/lang-powershell.env
test/lang-python.env
test/lang-ruby.env
test/lang-rust.env
test/lang-shell.env

Print interpreter version

---

.gitignore
Makefile
byexample/modules/iasm.py
byexample/modules/powershell.py
byexample/runner.py
docs/languages/ruby.md
docs/overview/faq.md
test/runner_version_matrix.py

Change some prints to make them machine-parseable

---

byexample/modules/shell.py
docs/languages/shell.md

Issue 230 more signals to stop

---

byexample/cmdline.py
byexample/init.py
byexample/modules/progress.py
byexample/runner.py
docs/advanced/unicode.md
docs/overview/usage.md
test/corner_cases.md
test/ds/binary-blob
test/ds/output-bin

Issue 232 support encoding error handler

---

byexample/concern.py
byexample/init.py
byexample/modules/clipboard.py
byexample/modules/powershell.py
byexample/modules/progress.py
byexample/modules/rust.py
byexample/options.py
byexample/runner.py
docs/contrib/concurrency-model.md
docs/contrib/extension-initialization.md
test/ds/bad/init/init_failed.py
test/ds/bad/pexpect_init/badrunner.py
test/ds/bad/target/invalid/bad.py
test/ds/bad/target/missing/bad.py
test/ds/submod/submod.py

Make parent class explicit (super() is not supported)

---

Makefile
setup.py
test/ds/terminal-ansi-unicode.md
test/minimum-term-ansi.env

Accept pyte 0.8.1

---

byexample/cfg.py
byexample/executor.py
byexample/init.py
byexample/options.py
docs/contrib/how-to-support-new-finders-and-languages.md
test/corner_cases.md
test/ds/dual.md

Issue 203 isolate language specific changes on generic options

---

byexample/modules/cpp.py
byexample/modules/elixir.py
byexample/modules/gdb.py
byexample/modules/go.py
byexample/modules/iasm.py
byexample/modules/java.py
byexample/modules/javascript.py
byexample/modules/php.py
byexample/modules/powershell.py
byexample/modules/python.py
byexample/modules/ruby.py
byexample/modules/rust.py
byexample/modules/shell.py
byexample/runner.py

Issue 258 add working directory to shebang
